

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: study-buddy-postgres
    environment:
      - POSTGRES_DB=study_buddy_db
      - POSTGRES_USER=study_buddy_user
      - POSTGRES_PASSWORD=study_buddy_password
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - study-buddy-network
  redis:
    image: redis:latest
    container_name: study-buddy-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks: 
      - study-buddy-network
    volumes:
      - redis_data:/data
  minio:
    image: minio/minio:latest
    container_name: study-buddy-minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio
      MINIO_DEFAULT_BUCKETS: study-buddy
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - study-buddy-network


networks:
  study-buddy-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  minio_data: