

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: study-buddy-postgres
    environment:
      - POSTGRES_DB=study_buddy_db
      - POSTGRES_USER=study_buddy_user
      - POSTGRES_PASSWORD=study_buddy_password
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - study-buddy-network
  redis:
    image: redis:latest
    container_name: study-buddy-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks: 
      - study-buddy-network
    volumes:
      - redis_data:/data
    


networks:
  study-buddy-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: